# Forum Groups

## Slack

[Government Data Science](https://govdatascience.slack.com/#/) - requires a recognised email address and not every NHS/Local Authority is listed. However, `nhs.net` is acceptable. 

[NHS-R Community](https://nhsrcommunity.slack.com) - predominantly R related but many channels like Git, Python and Ethics. Membership is open for anyone interested in health and social care.

## Platforms

[FutureNHS](https://future.nhs.uk/) - The FutureNHS Collaboration Platform is the only virtual collaboration platform from the NHS that supports people working in health and social care to make change, improve and transform across organisations, places and professions.


## National and International

* [Association of Professional Healthcare Analysts (AphA)](https://www.aphanalysts.org/) -  Aims to raise the profile of healthcare analysts and provide a professional support network. Membership organisation.
[NHS-R Community](https://nhsrcommunity.com/) - The NHS-R community aims to support the learning, application and exploitation of R in the NHS through workshops, video tutorials and providing a platform for discussion and sharing of developing best practice solutions to NHS problems.
* [Royal Statistical Society](https://www.rss.org.uk/RSS/Get_involved/Sections_and_study_groups/Data_Science/RSS/Get_involved/Sections/Data_Science_Section.aspx?hkey=81ae8d96-62d2-496c-b89c-3c8380313f61) - The Data Science Section is a newly formed section of the Royal Statistical Society that was established in 2017. The Section includes representatives from business, industry, government and academia and was formed to address emerging topics that will impact the long term success of data science as a profession.
* [UK Health Data Research Alliance](https://www.hdruk.ac.uk/digital-innovation-hubs/uk-health-data-research-alliance/) - The UK Health Data Research Alliance will unite expertise and act as a clearing house for best practice in the stewardship of the UK’s health data – including patient and administrative data from the NHS, genomic data and other molecular data – to enable faster, more efficient access for research at scale. This will speed up progress in science, medicine and healthcare at pace.
* [Open Data Leaders Network](https://theodi.org/project/open-data-leaders-network/) - The Open Data Institute (ODI) has developed the Open Data Leaders Network – a global peer network of public sector open data leaders at different levels (city, regional and national) – to promote peer-learning and knowledge exchange.
* [Deep Intelligence Telegram Group ](https://t.me/joinchat/CuFqkRQSxRy5M_6KxhKrCA) - The main topics discussed by the group include: Business Development and Business Model in Digital Transformation Age; Data Science; Artificial Intelligence; Machine Learning; Deep Learning; Cognitive Science, and; Neuroscience. 

## South West Local

* [Bristol Data Scientists Meetup](https://www.meetup.com/Bristol-Data-Scientists/) - The aim of this meetup is to promote discussion, learning and interaction around Data Science in the South West. This is a group for statisticians, mathematicians, programmers, data scientists, data alchemists and anyone interested in using data for analytics. Aim to run meetings on a quarterly basis
* [Bristol Project Data Analytics Meetup ](https://www.meetup.com/Bristol-Project-Data-Analytics-Meetup/) - Meetup to share best practise on leveraging data within a project, programme and portfolio environment. This meetup will explore some of the challenges at the intersection of data analysis and project, programme and portfolio management and discuss how practitioners are working to resolve them,
* [Elizabeth Blackwell Institute Health Data Science Research Strand](https://www.bristol.ac.uk/blackwell/health-research/research-strands/health-data-science/) - A University of Bristol group of academics with an interest in making better use of routinely collected data. 
* [Local Digital Health Research and Development Group](http://www.bristolhealthpartners.org.uk/about-us/local-digital-health-research-development-group/) - Bristol Health Partners convenes a Local Digital Health Research and Development Group, bringing together academics, NHS organisations and local authorities in Bristol, North Somerset and South Gloucestershire (BNSSG).
* [Southwest Data Meetup](https://www.meetup.com/south-west-data/) - The Bristol-based holistic data group that is all things to do with managing, handling, analysing and delivering data in the mild mild South West.
* Health Intelligence network - Staff from the local Clinical Commissioning Group and Sustainability and Transformation Partnership Business intelligence services are developing an intelligence network. 
