project:
  type: book
  resources:
    - CNAME
book:
# If you are forking our repo to develop content -- whether for NHS-R Community
  # or your own purposes -- please disable our Google Analytics tag during development.
  # If building your own site, replace our GA tag with your own GA tag before deployment.
  # This will prevent your activity being tracked and counted in our analytics dashboard.
  # Thank you!
  google-analytics: "G-70FNTNV7ZP"
  title: "Open Analytics Resources"
  author: "NHS-R Community"
  date: last-modified
  comments:
    hypothesis: true
    giscus:
      repo: nhs-r-community/open-analytics-resources
  chapters:
    - index.qmd
    - forum-groups.qmd
    - accessibility.qmd
    - ethics.qmd
    - reproducible-analytical-pipelines.qmd
    - tools.qmd
    - training.qmd
    - code-of-practice-regulation-guidance.qmd
    - profession.qmd
    - mapping-gis.qmd
    - knowledge-resource.qmd
    - data-collection.qmd
  page-footer:
    left: |
      Open Analytics Resources by the NHS-R Community

      NHS-R Community makes all of their materials publicly available under open source licenses
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/Lextuga007/open-analytics-resources
  repo-branch: main
  repo-actions: [edit, issue]
  site-url: https://github.com/Lextuga007/open-analytics-resources

format:
  html:
    theme: cosmo
