# Data collection resources

## Gender and Transgender

[Guidance](https://digital.nhs.uk/data-and-information/data-collections-and-data-sets/data-sets/mental-health-services-data-set/guidance-on-collecting-and-submitting-data-for-data-items-on-gender#data-items-on-gender-and-trans-status) on collecting and submitting data for the data items on gender within the Mental Health Services Data Set (MHSDS) is a useful resource for information on these protected characteristics.

## NHS Data Dictionary

The [NHS Data Model and Dictionary](https://www.datadictionary.nhs.uk/) has been developed for everyone who is actively involved in the collection of data and the management of information in the NHS.

## Population

[NOMIS official census and labour market statistics](https://www.nomisweb.co.uk/) - managed by Office for National Statistics publishing statistics related to population, society and the labour market at national, regional and local levels. 
Requires an account to save searches through API. 

An R package called [{nomisr}](#api)

[POPPI Projecting Older People Population Information](https://www.poppi.org.uk/) - requires registration. 

> Originally developed for the Department of Health, this system provides population data by age band, gender, ethnic group, and tenure, for English local authorities.

> Calculations are applied to population figures to estimate projected numbers of older people by; those living alone, living in care home, provision of unpaid care, their ability to carry out domestic tasks and self care.

> Prevalence rates from research have been used to estimate the impact of; limiting long term illness, depression, severe depression, dementia, heart attack, stroke, bronchitis\emphysema, falls, continence, visual impairment, hearing impairment, mobility, obesity, diabetes and learning disability including Down's syndrome and autistic spectrum disorders (ASD).

[PANSI Projecting Adult Needs and Service Information](https://www.pansi.org.uk/) - requires registration. 

> Originally developed for the Department of Health, this system provides population data by age band, gender, and ethnic group.

> Prevalence rates from research have been used to estimate the impact of: learning disability, including living with a parent, Down's syndrome, challenging behaviour, autistic spectrum disorders; moderate or serious physical disability including personal care, stroke, diabetes, visual impairment and hearing impairment; mental health problems including depression, neurotic, personality and psychotic disorders, drugs and alcohol, suicide, adult survivors of childhood sexual abuse and early onset dementia.

## Small number suppression

[Public Health Wales](https://phw.nhs.wales/about-us/policies-and-procedures/policies-and-procedures-documents/information-governance-information-management-and-technology-supporting-documents/small-numbers-publishing-guidance/) guidance in the Appendices is very useful in that it gives example situations for data suppression and how to handle them, including small denominator values, indirect disclosure and where self disclosure can cause distress.

[UK Data Service](https://ukdataservice.ac.uk/learning-hub/research-data-management/data-protection/disclosure-assessment/) assessing disclosure risk and managing risk has an example from a review showing the types of direct identifiers as well as variables affected by local knowledge.

[Statistical disclosure dos and don'ts](http://wp.lancs.ac.uk/administrative-data-research/2021/08/27/statistical-disclosure-the-dos-and-donts/) blog from Lancaster University.

[NHS Digital](https://digital.nhs.uk/data-and-information/data-tools-and-services/data-services/data-quality/data-quality-maturity-index-methodology/suppression-rules) Suppression Rules for different data sets.

[ONS](https://www.ons.gov.uk/methodology/methodologytopicsandstatisticalconcepts/disclosurecontrol/policyonprotectingconfidentialityintablesofbirthanddeathstatistics) Policy on protecting confidentiality in tables of birth and death statistics.

## Data Linkage

Specific online courses for data linkage is available through the [Analysis Function](#AF).

[Splink: Fast, accurate and scalable record linkage - Data in government (blog.gov.uk)](https://dataingovernment.blog.gov.uk/2022/09/23/splink-fast-accurate-and-scalable-record-linkage/).

[Health Economics Unit NHS Guide](https://healtheconomicsunit.nhs.uk/wp-content/uploads/2022/02/Data-linkage-guide_January-2022.pdf) - "This guide to data linkage was produced to support NHS systems (such as ICSs and STPs), commissioners, providers, NHS England and NHS Improvement and arm’s-length bodies to co-learn and co-develop, and to share and spread best practice, learning and tools relating to data linkage that extends beyond primary and secondary care".

[Faculty of Public Health - Health Knowledge](https://www.healthknowledge.org.uk/public-health-textbook/health-information/3b-sickness-health/data-linkage) - Data linkage within and across datasets
