# Ethics resources 

[Data Ethics Framework](https://www.gov.uk/government/publications/data-ethics-framework/data-ethics-framework-2020) - from Central Digital & Data Office
“The Data Ethics Framework guides appropriate and responsible data use in government and the wider public sector. 
It helps public servants understand ethical considerations, address these within their projects, and encourages responsible innovation.”

[The Data Hazards Project](https://datahazards.com/) - "Data Hazards is a project about worst-case scenarios of data science. Data scientists are great at selling our work, for example communicating the gains in efficiency and accuracy, but we are less well-practiced in thinking about the ethical implications of our work. The ethical implications go beyond most ethics Institutional Review Boards, to questions about the wider societal impact of data science and algorithms work." All resources are open source and open to contribution.

## Groups

[Data Ethics Club](https://dataethicsclub.com/) and very open [GitHub](https://github.com/very-good-science/data-ethics-club) - is a fortnightly discussion group/"journal" club about doing data science ethically. 
"Journal" because they also read blog posts, (parts of) books, or watch videos. 
The organisers are based in Bristol, but the club is open to all and is held virtually.

UK Government Data Science [Data Ethics and Society Reading Group](https://alphagov.github.io/data-ethics-and-society-reading-group/) - open to Government and Public Sector.
