# Forum Groups

## Slack

[Government Data Science](https://govdatascience.slack.com/#/) - requires a recognised email address and not every NHS/Local Authority is listed. 
However, `nhs.net` is acceptable. 

[NHS-R Community](https://nhsrcommunity.slack.com) - predominantly R related but many channels like Git, Python and Ethics. 
Membership is open for anyone interested in health and social care and not restricted to R.
As of 2022 hosted by [The Strategy Unit](https://www.strategyunitwm.nhs.uk/) part of NHS Midlands and Lancashire Commissioning Support Unit.

[NHS Pycom](https://nhs-pycom.slack.com) - predominately Python and run by volunteers.

## Platforms

[FutureNHS](https://future.nhs.uk/) - The FutureNHS Collaboration Platform is the only virtual collaboration platform from the NHS that supports people working in health and social care to make change, improve and transform across organisations, places and professions.

[KHub](https://khub.net/) - is a platform site often used by Civil Service and Local Authorities to share knowledge, insight and best practice.

## Community groups

### NHS and Public Sector groups

[NHS-R Community](https://nhsrcommunity.com/) - The NHS-R community aims to support the learning, application and exploitation of R in the NHS through workshops, video tutorials and providing a platform for discussion and sharing of developing best practice solutions to NHS problems.

[NHS Pycom](https://nhs-pycom.net/) - is an open community of practice that champions the use of the python programming language and open code in the NHS and healthcare sector.

[AnalystX](https://analystx.uk/) - is a community leading the movement for data driven, evidence-based decision making by sharing learning across health and social care.

### Global community groups

[R-girls](https://rgirls.org.uk/) a worldwide network to promote the use of R - a leading data science programming language - in secondary schools for girls.

[MiR](https://mircommunity.com/) is a Slack-based community started in March 2020 to support the professional development and well-being of historically underrepresented minorities that use R.

[R Ladies Global](https://rladies.org/) is an organization that promotes gender diversity in the community of users of the R statistical programming language.

## Midlands

[The Strategy Unit ](https://www.strategyunitwm.nhs.uk/) - The Strategy Unit is a specialist NHS team, based in NHS Midlands and Lancashire Commissioning Support Unit. 
They provide high-quality, multi-disciplinary analytical work as well as host the [Midlands Analyst Network](https://www.midlandsdecisionsupport.nhs.uk/communities-of-practice/midlands-analyst-network/) which is a fornightly virtual MS Teams meeting which is open to Network members.

## Coffee and Coding

NHS-R Community host a coffee and coding every other Friday at 11:00 – 12:00.
Details are on the [blog](https://nhsrcommunity.com/coffee-and-code/).
