--- 
title: " Open Analytics Resources"
author: "Zoë Turner"
date: "Last Updated `r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  A set of resources for NHS Analysis.
link-citations: yes
github-repo: nhs-r-community/statements-on-tools
nocite: '@*'
---

# Open Analytics Resources for Health and Care {#intro}

Originally a [Google document](https://docs.google.com/document/d/15unzokDyUQR_YLWFqBwVvds3C6B69sZn_3OQro9gB3E/edit#) is supported by the [Association of Professional Healthcare Analysts (ApHA)](https://www.aphanalysts.org/), [This Equals](http://thisequals.co.uk/) and [Keyah Consulting](https://keyahconsulting.com/), in collaboration with the [Health Foundation](https://health.org.uk/), released under a CC-BY-SA licence. Attributions to ApHA 2020. This document is still active.

This document is a resource for analysts and data scientists working in the health and care sectors primarily, but not exclusively, in the UK.

## Technical notes 

This {bookdown} is available for review, curation, comment and update from anyone who wishes to do a pull request or an [issue](https://github.com/Lextuga007/open-analytics-resources/issues). Using GitHub means this is version controlled, is backed up and is available to everyone.

Translation from the Google document was via a copy to a personal account and the use of the Google Add-On for turning docs to markdown. 

