# Open Analytics Resources for Health and Care {#intro}

Originally a [Google document](https://docs.google.com/document/d/15unzokDyUQR_YLWFqBwVvds3C6B69sZn_3OQro9gB3E/edit#) is supported by the [Association of Professional Healthcare Analysts (ApHA)](https://www.aphanalysts.org/), [This Equals](http://thisequals.co.uk/) and [Keyah Consulting](https://keyahconsulting.com/), in collaboration with the [Health Foundation](https://health.org.uk/), released under a CC-BY-SA licence. 
Attributions to AphA 2020. 
Later this was copied by Zoë Turner into {bookdown} and now has been converted into a Quarto book to be shared through the NHS-R Community.
This document is still active.

This document is a resource for analysts and data scientists working in the health and care sectors primarily, but not exclusively, in the UK and includes many links to resources produced and maintained by Public Sector and Government teams.

## Technical notes 

This Quarto book is available for review, curation, comment and update from anyone who wishes to do a pull request or an issue (links will appear on each page to edit or report and issue). 
Using GitHub means this is version controlled, is backed up and is available to everyone.

Translation from the Google document was via a copy to a personal account and the use of the Google Add-On for turning docs to markdown. 
