# Mapping/GIS resources

[SHAPE Atlas](https://shapeatlas.net/) - "is an online, interactive, data mapping, analysis and insight tool that supports service planning and estates strategy development." Requires registration from a public sector email.

Includes travel times for public transport and car, demographics and building locations amongst other data.

Managed by the Department of Health and Social Care

[Local Health](https://www.localhealth.org.uk/#c=home) - "Quality assured small area health-related data visualised in maps, charts, area profiles, and reports." Managed by the Office for Health Improvement and Disparities (OHID) and allows for uploading of your own data.

## Centroid mapping

Sometimes you have a set of addresses but no way of mapping them. [The Office for National Statistics’ Open Geography Portal](http://geoportal.statistics.gov.uk/datasets/ons-postcode-directory-latest-centroids) provides the centroids for all UK postcodes.

Using R to get centroid information: https://www.trafforddatalab.io/recipes/gis/postcodes.html#

Or weighted by LSOA area: https://geoportal.statistics.gov.uk/datasets/lower-layer-super-output-areas-december-2011-population-weighted-centroids

Taken from [a blog](https://cdu-data-science-team.github.io/team-blog/posts/2021-05-14-mapping/) by the CDU Team.

## Travel times

[Wales-ish OTP Graph Generator](https://github.com/stupidpupil/wales_ish_otp_graph) - "assemble OpenTripPlanner, R5 and OSRM graphs that are useable for planning trips, by car or public transport, between places in Wales - including where these trips involve a short journey entirely within England. (It likely also works well enough for planning trips between places in Wales and a small number of English towns just the other side of the border.)"

[Data Science Campus blog](https://datasciencecampus.ons.gov.uk/using-open-data-to-understand-hyperlocal-differences-in-uk-public-transport-availability/) - using open data to understand hyperlocal differences in uk public transport availability.

[Using {sf} to calculate catchment areas](https://nhsrcommunity.com/using-sf-to-calculate-catchment-areas/) - from NHS-R blogs.

[NHS Pycom nhs_time_of_travel](https://github.com/nhs-pycom/nhs_time_of_travel) - a collaborative open source project between NHS Python Community and Google Health, building on https://github.com/nhsx/nhs_time_of_travel
