# Tools and Resources 

[NHS-R Community Statement on Tools](https://nhs-r-community.github.io/statements-on-tools/) is a collaborative effort by the community inspired initially from difficulties faced when installing free tools such as R and R Studio. 

## NHS Number/CHI number validation

### R packages

#### England NHS Number

[{nhsnumber}](https://github.com/cran/nhsnumber) - An R package to work with NHS numbers and their checksums.
Available through CRAN.
Referred to in an NHSR Community blog [The “nhsnumber” package and the joy of sharing your niche](https://nhsrcommunity.com/the-nhsnumber-package-and-the-joy-of-sharing-your-niche/).

[nhsnumbergenerator](https://github.com/samellisq/nhsnumbergenerator) - Generates Random NHS Numbers in R.
Note, no licence.

### Scottish CHI Number

[{phsmethods}](https://github.com/Public-Health-Scotland/phsmethods/tree/master) - available on CRAN. A collection of methods for commonly undertaken analytical tasks, primarily developed for Public Health Scotland (PHS) analysts, but the package is also generally useful to others working in the healthcare space, particularly since it has functions for working with Community Health Index (CHI) numbers. The package can help to make data manipulation and analysis more efficient and reproducible.

### Python packages

[nhs-number](https://github.com/uk-fci/nhs-number) - provides utilities for NHS Numbers, including validity checks, normalisation, and generation.

## Git resources

[Git Command Glossary](https://github.com/datasciencecampus/gov-uk-rap-materials/blob/main/git-glossary/git-command-glossary.csv) part of the [Gov UK RAP Materials](https://github.com/datasciencecampus/gov-uk-rap-materials/tree/main).

## APIs/packages {#api}

### Python packages

[Health indicator data sources](https://github.com/NIHR-BI/Health_Indicators/tree/main) from NIHR National Institute for Health and Care Research using Python

### R packages

[{nomisr}](https://docs.evanodell.com/nomisr/articles/introduction.html) can be used to access the API which can be built from the [webpage](https://www.nomisweb.co.uk/).

[{onsr}](https://kvasilopoulos.github.io/onsr/) in Beta for ONS data.

[{fingertipsR}](https://docs.ropensci.org/fingertipsR/) for Public Health data also available through the [website](https://fingertips.phe.org.uk/).

[{boundr}](https://francisbarton.github.io/boundr/) to retrieve area boundaries and data from the ONS Open Geography Portal.

[{lonlatapi}](https://github.com/francisbarton/lonlatapi)finds OA (Census output area) data from longitude and latitude data. Depends upon {boundr} being loaded.

[{NHSRpostcodetools}](https://github.com/nhs-r-community/NHSRpostcodetools) package to work with England Postcodes in R
