# Training and development opportunities

## Public Sector Resources 

### NHS-R Community
[NHS-R Community](https://nhsrcommunity.com/) - record all webinars and have conference talks and workshops from 2020 onwards found through the website which links to [YouTube](https://nhsrcommunity.com/). Introduction to R and R Studio training is being provided by volunteers each month with more training always encouraged and listed on the website.

The [NHS-R Community Training](https://training.nhsrcommunity.com/) book (built in Quarto) collects together the course summaries for training materials available through NHS-R Community and delivered as instructor led courses through [The Strategy Unit](https://nhs-r-community.github.io/NHSR-training/strategy-unit.html).

### Government {#AF}
* [Data Science Campus](https://datasciencecampus.ons.gov.uk/) - with training and services for Government and Public Sector (which includes NHS and Local Authorities). Check for public sector status for [Departments, agencies and public bodies](https://www.gov.uk/government/organisations), note that this does not list every NHS organisation or Local Authority but does not mean they are excluded.

* [Analysis Function training courses](https://analysisfunction.civilservice.gov.uk/training-courses/) sign up as a public sector/government person via [Data.Science.Campus.Faculty@ons.gov.uk](mailto:Data.Science.Campus.Faculty@ons.gov.uk)

### HSMA - Health Service Modelling Associates programme

[YouTube channel](https://www.youtube.com/channel/UCCY9_Gxg6kM-xjk9vV0mzIQ) for teaching materials for the NIHR Applied Research Collaboration South West Peninsula (PenARC) [Health Service Modelling Associates programme](https://sites.google.com/nihr.ac.uk/hsma).

#### Specific related links

* [UK GOV- Government Analysis Function - Learning Curriculum](https://www.gov.uk/guidance/government-analysis-function-af-learning-curriculum) - “Whether you’re an experienced government analyst looking to refresh or develop your skills, or brand new to your role, a member of one (or more) of the analytical professions or not, the AF Learning Curriculum has something for everyone.”

* [Analysis Function training catalogue](https://analysisfunction.civilservice.gov.uk/training-courses/) - all the online courses as detailed in the Curriculum, free after signing up via [Data.Science.Campus.Faculty@ons.gov.uk](mailto:Data.Science.Campus.Faculty@ons.gov.uk)

* [Data Masterclass for Senior Leaders](https://datasciencecampus.ons.gov.uk/capability/data-masterclass-for-senior-leaders/) - delivered from the campus and available to all public sector. 

## Other online free courses

* [HDR UK Futures for NHS](https://www.hdruk.ac.uk/futures-nhs/) - free online course materials available for anyone. Sign up required.

* [FEDIP courses](https://www.fedip.org/fedip-hub) - free for 6 months or free with an AphA membership(https://www.aphanalysts.org/) with CPD on courses from the University of Edinburgh. Includes introduction to Health Data Analytics with R, Introduction to Data Visualisation and Data Ethics for Health and Social Care. Sign up required.

* [W3Schools](https://www.w3schools.com/) has tutorials and reference guides for a large number of software programs including Python, R, SQL, CSS and html.

## MOOC (Massive Open Online Course)

### Future Learn

* [Data Science for Healthcare: Using Real World Evidence](https://www.futurelearn.com/courses/data-science-healthcare)
* [Health data analytics](https://www.futurelearn.com/courses/eit-health-data-analytics)
* [Quality Improvement in Healthcare: the Case for Change](https://www.futurelearn.com/courses/quality-improvement)

## Funding 

* HDRUK fund [Masters Courses](https://www.hdruk.ac.uk/careers-in-health-data-science/further-education/masters-programme/) at particular Universities. 

## Specific software

### Introduction to R and R Studio

* The first Introduction to R and RStudio slides [published through GitHub](https://nhs-r-community.github.io/intro_r/) with the [GitHub repository](https://github.com/nhs-r-community/intro_r).

* The latest Introduction to R and RStudio which is modular and has enough content for 3 half days can be found in the [NHS-R Training book](https://training.nhsrcommunity.com/).

* [Analysis Function](#AF) free online training to public sector and government employees [Introduction to Git](https://analysisfunction.civilservice.gov.uk/training/introduction-to-r/).

* NHS England [R Programming Language](https://nhsengland.github.io/nhs-r-reporting/tutorials/r-language.html) in a Quarto site for self learning.

### Introduction to RMarkdown

* [A workshop](https://github.com/nhs-r-community/intro_rmd) from the NHS-R Conference in 2021 based on the scripted way of delivering courses.

* A slide based [course on RMarkdown](https://github.com/nhs-r-community/rmarkdown_intro) which was based on the conference workshop.

* NHS England [Quarto and RMarkdown](NHS England [GitHub training](https://nhsengland.github.io/nhs-r-reporting/tutorials/github.html) in a Quarto site for self learning.

### Git/GitHub

* [A workshop](https://github.com/nhs-r-community/git_training) from the NHS-R Conference in 2022 based on the scripted way of delivering courses and using the Terminal.

* Not NHS-R but from the [NHS North Central London ICB Analytics Team](https://github.com/ncl-icb-analytics) an [Introduction to Git and GitHub](https://ncl-icb-analytics.github.io/intro_to_git/intro_slides.html#1) on the command line using a slide format.

* NHS England [GitHub training](https://nhsengland.github.io/nhs-r-reporting/tutorials/github.html) in a Quarto site for self learning.

* [Analysis Function](#AF) free online training to public sector and government employees [Introduction to Git](https://analysisfunction.civilservice.gov.uk/training/introduction-to-git/).

* Free [Git course](https://www.futurelearn.com/courses/collaborative-coding-with-git) on the FutureLearn MOOC platform.

### Introduction to Python

* [Analysis Function](#AF) free online training to public sector and government employees [Introduction to Python](https://analysisfunction.civilservice.gov.uk/training/introduction-to-python/).

### Modular programming in Python and R

* [Analysis Function](#AF) free online training to public sector and government employees [Introduction to Python and R](https://analysisfunction.civilservice.gov.uk/training/modular-programming-in-python-and-r/).

### SQL

* Free SQL training can be found on MOOCs and a particularly good one that has been split into smaller "mini-courses" is by [Stanford University](https://online.stanford.edu/courses/soe-ydatabases-databases) via the [Edx platform](https://www.edx.org/learn/sql). 

* The [SQL Murder Mystery](https://mystery.knightlab.com/) - The SQL Murder Mystery is designed to be both a self-directed lesson to learn SQL concepts and commands and a fun game for experienced SQL users to solve an intriguing crime.

* [Foundations of Structured Query Language (SQL)](https://analysisfunction.civilservice.gov.uk/training/foundations-of-sql/?_rt=MXwxfHNxbHwxNzA4MzU5NDIz&_rt_nonce=8a53a1f22c) - 1 day online course from the [Analysis Function](#AF).

* [Software Carpentry](https://swcarpentry.github.io/sql-novice-survey/)

* [Khan Academy](https://www.khanacademy.org/computing/computer-programming/sql)

* [Kaggle](https://www.kaggle.com/learn/intro-to-sql)

* [SQLzoo Wiki page](https://sqlzoo.net/wiki/SQL_Tutorial)

* Blogs 
    - <https://www.kdnuggets.com/5-free-university-courses-to-learn-databases-and-sql>
    - <https://www.kdnuggets.com/5-free-courses-to-master-sql-for-data-science>
    


### Introduction to Reproducible Analytical Pipelines (RAP) {#rap-training}

Also see the specific chapter on [RAP](#RAP)

* [Analysis Function](#AF) free online training to public sector and government employees [Introduction to Reproducible Analytical Pipelines (RAP)](https://analysisfunction.civilservice.gov.uk/training/introduction-to-reproducible-analytical-pipelines-rap/).

* NHS England [Reproducible Analytical Pipelines (RAP)](https://nhsengland.github.io/nhs-r-reporting/tutorials/rap.html) in a Quarto site for self learning.

### Train the Trainer

* [Slides](https://github.com/nhs-r-community/train_the_trainer) from a Train the Trainer course held by the Strategy Unit to support the Introduction to R and RStudio.
